# Generated by Django 5.2.6 on 2025-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional header image for the post.', null=True, upload_to='blogs/'),
        ),
    ]
