# Generated by Django 5.2.6 on 2025-10-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text="Subscriber's email address", max_length=254, unique=True, verbose_name='Email Address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unsubscribed', 'Unsubscribed')], default='active', max_length=20, verbose_name='Status')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
